import { Inter } from "next/font/google";
import "./globals.css";
import styles from "@/componenets/content/sideBar.module.css"
import Header from "@/componenets/header/header";
import PrimaryMenu from "@/componenets/navigation/primaryMenu";
import Footer from "./footer/page";
import SideBar from "@/componenets/content/sideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My personal blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div>
      <Header></Header>
      <PrimaryMenu></PrimaryMenu>
        
        {children}
       </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
